version: '3.9'

services:
  health-code:
    image: pexcn/health-code:latest
    container_name: health-code
    restart: unless-stopped
    network_mode: host
    environment:
      TZ: Asia/Taipei
    volumes:
      - ./health-code-data/conf/health-code.conf:/etc/nginx/conf.d/health-code.conf
      - ./health-code-data/cert:/etc/nginx/cert
