name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docker-compose.yml'
      - '**.md'
  schedule:
    # daily at 22:00 UTC
    #- cron: "0 14 * * *"

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    env:
      TZ: Asia/Taipei

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set environment variables
        run: echo "CURRENT_DATE=$(date +%Y%m%d)" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and Push to Container Registries
        uses: docker/build-push-action@v3
        with:
          tags: |
            ${{ github.repository }}:latest
            ${{ github.repository }}:${{ env.CURRENT_DATE }}
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ env.CURRENT_DATE }}
          platforms: linux/amd64,linux/arm64
          push: true
